version: '3'

volumes:
  pg_data_kittygram:
  static:
  media: 

services:
  db_kittygram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    image: rtimonin569/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db_kittygram
  frontend:
    image: rtimonin569/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: rtimonin569/kittygram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    ports:
      - 9000:80
